using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SimpleLocalizations.Generator;

/// <summary>
/// Writes the body of every <c>[VocabularyKey]</c> type.
/// <para>
/// The shape is the rule, so it is generated rather than asked for: a private constructor and one public
/// factory are what keep a vocabulary closed, and a hand-rolled type that grew a public constructor would
/// open it again with nothing failing. What a consumer declares is the name.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class KeyTypeGenerator : IIncrementalGenerator
{
    private const string _marker = "SimpleLocalizations.VocabularyKeyAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var keyTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _marker,
                static (node, _) => node is TypeDeclarationSyntax,
                static (target, _) => Describe(target))
            .Where(static described => described is not null)
            .Select(static (described, _) => described!.Value);

        context.RegisterSourceOutput(keyTypes, static (production, keyType) => Produce(production, keyType));
    }

    private static KeyType? Describe(GeneratorAttributeSyntaxContext target)
    {
        // TypeDeclarationSyntax rather than StructDeclarationSyntax: a `record struct` is a
        // RecordDeclarationSyntax, and matching only the latter would silently skip every one of them.
        if (target.TargetSymbol is not INamedTypeSymbol symbol
            || target.TargetNode is not TypeDeclarationSyntax declaration)
        {
            return null;
        }

        return new KeyType(
            symbol.Name,
            symbol.ContainingNamespace.IsGlobalNamespace ? "" : symbol.ContainingNamespace.ToDisplayString(),
            declaration.Modifiers.Any(modifier => modifier.ValueText == "partial"),
            symbol.IsRecord,
            Accessibility(symbol));
    }

    private static void Produce(SourceProductionContext production, KeyType keyType)
    {
        if (!keyType.IsPartial)
        {
            production.ReportDiagnostic(Diagnostic.Create(
                VocabularyDiagnostics.NotPartial, Location.None, keyType.Name));
            return;
        }

        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (keyType.Namespace.Length > 0)
        {
            source.AppendLine($"namespace {keyType.Namespace};");
            source.AppendLine();
        }

        source.AppendLine("/// <summary>");
        source.AppendLine("/// The body of a vocabulary key: a private constructor and one factory, so a key can only come");
        source.AppendLine("/// from the generated declaration that authors it.");
        source.AppendLine("/// </summary>");
        source.AppendLine($"{keyType.Access} readonly partial {(keyType.IsRecord ? "record " : "")}struct {keyType.Name}");
        source.AppendLine("{");
        source.AppendLine($"    private {keyType.Name}(string key) => Key = key;");
        source.AppendLine();
        source.AppendLine("    /// <summary>The dotted key the catalog resolves.</summary>");
        source.AppendLine("    public string Key { get; }");
        source.AppendLine();
        source.AppendLine("    /// <summary>The generated declaration's constructor.</summary>");
        source.AppendLine($"    public static {keyType.Name} From(string key) => new(key);");
        source.AppendLine();
        source.AppendLine("    /// <inheritdoc />");
        source.AppendLine("    public override string ToString() => Key ?? \"\";");
        source.AppendLine("}");

        production.AddSource(
            $"{(keyType.Namespace.Length == 0 ? "" : keyType.Namespace + ".")}{keyType.Name}.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// The declared accessibility, spelled the way the partial has to repeat it. Anything narrower than
    /// <c>public</c> is a consumer's business — the guard is a rule, not a modifier.
    /// </summary>
    private static string Accessibility(INamedTypeSymbol symbol) =>
        symbol.DeclaredAccessibility switch
        {
            Microsoft.CodeAnalysis.Accessibility.Public => "public",
            Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
            Microsoft.CodeAnalysis.Accessibility.Private => "private",
            Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
            Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
            Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
            _ => "internal",
        };

    /// <summary>A key type and the little the generator needs to write its body.</summary>
    private readonly struct KeyType : IEquatable<KeyType>
    {
        public KeyType(string name, string @namespace, bool isPartial, bool isRecord, string access)
        {
            Name = name;
            Namespace = @namespace;
            IsPartial = isPartial;
            IsRecord = isRecord;
            Access = access;
        }

        public string Name { get; }

        public string Namespace { get; }

        public bool IsPartial { get; }

        public bool IsRecord { get; }

        public string Access { get; }

        public bool Equals(KeyType other) =>
            Name == other.Name && Namespace == other.Namespace && IsPartial == other.IsPartial
            && IsRecord == other.IsRecord && Access == other.Access;

        public override bool Equals(object? obj) => obj is KeyType other && Equals(other);

        public override int GetHashCode() =>
            (Name, Namespace, IsPartial, IsRecord, Access).GetHashCode();
    }
}
