using System.Text;

namespace SimpleLocalizations.Generator;

/// <summary>Writes a vocabulary tree out as nested static classes, one member per authored key.</summary>
internal static class VocabularyEmitter
{
    /// <summary>
    /// The C# source for one vocabulary: a static class named <paramref name="className"/> in the declared
    /// namespace, holding a nested class per family and a key property per authored entry. Called once the tree
    /// is known to be emittable — every collision is reported before this runs.
    /// </summary>
    public static string Emit(
        VocabularyNode root, string @namespace, string className, VocabularyKeyTypes keyTypes, string resourceName)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine($"namespace {@namespace};");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// The keys this project authors, generated from its <c>.resx</c>. The resource file is the");
        source.AppendLine("/// declaration: a key renamed there moves this with it, and a producer naming one that is no");
        source.AppendLine("/// longer authored stops compiling.");
        source.AppendLine("/// </summary>");
        source.AppendLine($"public static class {className}");
        source.AppendLine("{");

        if (resourceName.Length > 0)
        {
            // The one thing a call site would otherwise spell by hand, and the one it cannot check: a base
            // name that does not match what the assembly embedded resolves nothing and throws on first use.
            source.AppendLine("    /// <summary>The resource set these keys are authored in.</summary>");
            source.AppendLine($"    public const string ResourceName = \"{resourceName}\";");
            source.AppendLine();
            source.AppendLine("    /// <summary>A catalog over this resource set, for <paramref name=\"cultures\"/>.</summary>");
            source.AppendLine("    public static global::SimpleLocalizations.StringCatalog Catalog(");
            source.AppendLine("        global::SimpleLocalizations.TextCultures cultures) =>");
            source.AppendLine($"        cultures.Catalog(ResourceName, typeof({className}).Assembly);");
            source.AppendLine();
        }

        foreach (var child in root.Children)
        {
            Write(source, child, keyTypes, indent: 1);
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static void Write(StringBuilder source, VocabularyNode node, VocabularyKeyTypes keyTypes, int indent)
    {
        var pad = new string(' ', indent * 4);

        if (node.Entry is { } entry)
        {
            Document(source, pad, entry.Comment is null
                ? $"The <c>{Escape(entry.Key)}</c> entry."
                : Escape(entry.Comment));
            var keyType = keyTypes.For(entry.Key);
            source.AppendLine($"{pad}public static global::{keyType} {VocabularyMember.Name(node.Segment)} =>");
            source.AppendLine($"{pad}    global::{keyType}.From(\"{entry.Key}\");");
            source.AppendLine();
            return;
        }

        Document(source, pad, $"The <c>{Escape(node.Path)}</c> family.");
        source.AppendLine($"{pad}public static class {VocabularyMember.Name(node.Segment)}");
        source.AppendLine($"{pad}{{");
        source.AppendLine($"{pad}    /// <summary>The stem every key in this family shares.</summary>");
        source.AppendLine($"{pad}    public const string Prefix = \"{node.Path}.\";");
        source.AppendLine();
        source.AppendLine($"{pad}    /// <summary>Whether <paramref name=\"key\"/> belongs to this family.</summary>");
        source.AppendLine($"{pad}    public static bool Covers(string key) =>");
        source.AppendLine($"{pad}        key.StartsWith(Prefix, global::System.StringComparison.Ordinal);");
        source.AppendLine();

        foreach (var child in node.Children)
        {
            Write(source, child, keyTypes, indent + 1);
        }

        source.AppendLine($"{pad}}}");
        source.AppendLine();
    }

    private static void Document(StringBuilder source, string pad, string text)
    {
        source.AppendLine($"{pad}/// <summary>{text}</summary>");
    }

    private static string Escape(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
