using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SimpleLocalizations.Generator;

/// <summary>Writes a vocabulary tree out as nested static classes, one member per authored key.</summary>
internal static class VocabularyEmitter
{
    /// <summary>The characters an XmlDoc summary cannot carry as written.</summary>
    private static readonly char[] _markup = ['&', '<', '>'];

    /// <summary>
    /// The C# source for one vocabulary: a static class named <paramref name="className"/> in the declared
    /// namespace, holding a nested class per family and a key property per authored entry. Called once the tree
    /// is known to be emittable — every collision is reported before this runs.
    /// </summary>
    public static SourceText Emit(
        VocabularyNode root,
        string @namespace,
        string className,
        VocabularyKeyTypes keyTypes,
        string resourceName,
        VocabularyFamilySets families)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("namespace ").Append(@namespace).AppendLine(";");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// The keys this project authors, generated from its <c>.resx</c>. The resource file is the");
        source.AppendLine("/// declaration: a key renamed there moves this with it, and a producer naming one that is no");
        source.AppendLine("/// longer authored stops compiling.");
        source.AppendLine("/// </summary>");
        source.Append("public static class ").AppendLine(className);
        source.AppendLine("{");

        if (resourceName.Length > 0)
        {
            // The one thing a call site would otherwise spell by hand, and the one it cannot check: a base
            // name that does not match what the assembly embedded resolves nothing and throws on first use.
            source.AppendLine("    /// <summary>The resource set these keys are authored in.</summary>");
            source.Append("    public const string ResourceName = \"").Append(resourceName).AppendLine("\";");
            source.AppendLine();
            source.AppendLine("    /// <summary>A catalog over this resource set, for <paramref name=\"cultures\"/>.</summary>");
            source.AppendLine("    public static global::SimpleLocalizations.StringCatalog Catalog(");
            source.AppendLine("        global::SimpleLocalizations.TextCultures cultures) =>");
            source.Append("        cultures.Catalog(ResourceName, typeof(").Append(className).AppendLine(").Assembly);");
            source.AppendLine();
        }

        var indents = Indents(root);

        foreach (var child in root.Children)
        {
            Write(source, child, keyTypes, families, indents, indent: 1);
        }

        source.AppendLine("}");
        return Text(source);
    }

    /// <summary>
    /// The finished document as the text Roslyn takes, read out of the buffer rather than through a string of
    /// it. <see cref="StringBuilder.ToString"/> is one more copy of the whole document, and past a size
    /// Roslyn's own reader knows, that copy is a single object on the large object heap.
    /// </summary>
    private static SourceText Text(StringBuilder source)
    {
        using var reader = new BufferReader(source);

        return SourceText.From(reader, source.Length, Encoding.UTF8);
    }

    /// <summary>
    /// The padding each level is written at, one string per level rather than one per node: every line a node
    /// writes opens with the same indent, and a vocabulary holds far more nodes than it has levels.
    /// </summary>
    private static string[] Indents(VocabularyNode root)
    {
        var indents = new string[Depth(root)];

        for (var level = 0; level < indents.Length; level++)
        {
            indents[level] = new string(' ', level * 4);
        }

        return indents;
    }

    /// <summary>How many levels <paramref name="node"/> nests, counting itself.</summary>
    private static int Depth(VocabularyNode node)
    {
        var deepest = 0;

        foreach (var child in node.Children)
        {
            deepest = Math.Max(deepest, Depth(child));
        }

        return deepest + 1;
    }

    private static void Write(
        StringBuilder source,
        VocabularyNode node,
        VocabularyKeyTypes keyTypes,
        VocabularyFamilySets families,
        string[] indents,
        int indent)
    {
        var pad = indents[indent];

        if (node.Entry is { } entry)
        {
            if (entry.Comment is { } comment)
            {
                Document(source, pad, "", comment, "");
            }
            else
            {
                Document(source, pad, "The <c>", entry.Key, "</c> entry.");
            }

            var keyType = keyTypes.For(entry.Key);
            source.Append(pad).Append("public static global::").Append(keyType).Append(' ')
                .Append(VocabularyMember.Name(node.Segment)).AppendLine(" =>");
            source.Append(pad).Append("    global::").Append(keyType)
                .Append(".From(\"").Append(entry.Key).AppendLine("\");");
            source.AppendLine();
            return;
        }

        Document(source, pad, "The <c>", node.Path, "</c> family.");
        source.Append(pad).Append("public static class ").AppendLine(VocabularyMember.Name(node.Segment));
        source.Append(pad).AppendLine("{");
        source.Append(pad).AppendLine("    /// <summary>The stem every key in this family shares.</summary>");
        source.Append(pad).Append("    public const string Prefix = \"").Append(node.Path).AppendLine(".\";");
        source.AppendLine();
        source.Append(pad).AppendLine("    /// <summary>Whether <paramref name=\"key\"/> belongs to this family.</summary>");
        source.Append(pad).AppendLine("    public static bool Covers(string key) =>");
        source.Append(pad).AppendLine("        key.StartsWith(Prefix, global::System.StringComparison.Ordinal);");
        source.AppendLine();

        if (families.For(node.Path) is { } set)
        {
            Lookup(source, node, set, keyTypes.For(node.Path), pad);
        }

        foreach (var child in node.Children)
        {
            Write(source, child, keyTypes, families, indents, indent + 1);
        }

        source.Append(pad).AppendLine("}");
        source.AppendLine();
    }

    /// <summary>
    /// The lookup from a declared set's member to the key wording it, written into the family the words are
    /// authored under. A member with no key authored is left out of the switch rather than pointed at a member
    /// that does not exist — <c>SL1011</c> is what names it, and the arm it would have taken throws.
    /// </summary>
    private static void Lookup(
        StringBuilder source, VocabularyNode node, FamilySet set, string keyType, string pad)
    {
        source.Append(pad)
            .AppendLine("    /// <summary>The key <paramref name=\"member\"/> is worded by.</summary>");
        source.Append(pad).Append("    ").Append(set.Exposed ? "public" : "internal")
            .Append(" static global::").Append(keyType).Append(" Of(").Append(set.Type).AppendLine(" member) =>");
        source.Append(pad).AppendLine("        member switch");
        source.Append(pad).AppendLine("        {");

        foreach (var member in set.Members)
        {
            if (Worded(node, member.Word) is { } worded)
            {
                source.Append(pad).Append("            ").Append(set.Type).Append('.').Append(member.Name)
                    .Append(" => ").Append(worded).AppendLine(",");
            }
        }

        source.Append(pad).AppendLine(
            "            _ => throw new global::System.ArgumentOutOfRangeException(nameof(member)),");
        source.Append(pad).AppendLine("        };");
        source.AppendLine();
    }

    /// <summary>
    /// The member name <paramref name="word"/> is emitted as under <paramref name="node"/>, or
    /// <see langword="null"/> where the family holds no key of its own by that word — unauthored, dropped as a
    /// collision, or a family in its own right, which is a class and not a key.
    /// </summary>
    private static string? Worded(VocabularyNode node, string word)
    {
        foreach (var child in node.Children)
        {
            if (child.Segment == word)
            {
                return child.Entry is null ? null : VocabularyMember.Name(child.Segment);
            }
        }

        return null;
    }

    /// <summary>
    /// One member's XmlDoc. Only <paramref name="text"/> is authored and so only it is escaped;
    /// <paramref name="before"/> and <paramref name="after"/> are the emitter's own markup around it.
    /// </summary>
    private static void Document(
        StringBuilder source, string pad, string before, string text, string after)
    {
        source.Append(pad).Append("/// <summary>").Append(before);
        Escape(source, text);
        source.Append(after).AppendLine("</summary>");
    }

    /// <summary>
    /// <paramref name="text"/> with the three characters XmlDoc reads as markup written as entities. Scanned
    /// once rather than rewritten three times, which is what a note carrying one of them costs: two
    /// intermediate strings on its way to the buffer.
    /// </summary>
    private static void Escape(StringBuilder source, string text)
    {
        if (text.IndexOfAny(_markup) < 0)
        {
            source.Append(text);
            return;
        }

        foreach (var character in text)
        {
            switch (character)
            {
                case '&':
                    source.Append("&amp;");
                    break;
                case '<':
                    source.Append("&lt;");
                    break;
                case '>':
                    source.Append("&gt;");
                    break;
                default:
                    source.Append(character);
                    break;
            }
        }
    }

    /// <summary>
    /// A reader over the buffer, which is what <see cref="SourceText.From(TextReader, int, Encoding, SourceHashAlgorithm)"/>
    /// takes. Roslyn then holds the document in chunks it sized itself; handing it a string means the whole
    /// document exists twice at once.
    /// </summary>
    private sealed class BufferReader : TextReader
    {
        private readonly StringBuilder _source;
        private int _position;

        public BufferReader(StringBuilder source) => _source = source;

        public override int Peek() => _position < _source.Length ? _source[_position] : -1;

        public override int Read() => _position < _source.Length ? _source[_position++] : -1;

        public override int Read(char[] buffer, int index, int count)
        {
            var read = Math.Min(count, _source.Length - _position);

            _source.CopyTo(_position, buffer, index, read);
            _position += read;

            return read;
        }
    }
}
