using SimpleLocalizations.Generator;
using static SimpleLocalizations.Tests.VocabularyHarness;

namespace SimpleLocalizations.Tests;

/// <summary>
/// The whole emitted document, for one vocabulary that reaches every branch of the emitter.
/// <para>
/// The rest of the suite asserts fragments, which is the right shape for a feature — it is why the emitter
/// can be rewritten without rewriting the suite — but a fragment says nothing about the text around it. A
/// change to how the source is built is verified here by this diff being empty. Where it is not, the diff is
/// the thing to read: the output changed, and that is either the point of the commit or its bug.
/// </para>
/// </summary>
public class VocabularySourceTests
{
    /// <summary>
    /// A flat key, a two-level family, a three-level family, a documented entry and an undocumented one, a
    /// segment naming a member the classes carry themselves, a segment opening with a digit, a family
    /// declaring its own key type, and a resource name.
    /// </summary>
    private static Run Emitted() =>
        Generate(
            Resx(
                ("greeting", "Hello", null),
                ("alpha.one", "One", "Names <c>a &amp; b</c>, where a &lt; b &gt; c."),
                ("alpha.prefix", "Prefix", null),
                ("beta.deep.three", "Three", null),
                ("detail.1password", "1Password", null)),
            new Declaration(
                "ProbeKeys", "Probe.ProbeKey | detail=Probe.OtherKey", "Probe", ResourceName: "Probe.Strings"));

    [Fact]
    public void A_vocabulary_reaching_every_branch_emits_exactly_this()
    {
        var run = Emitted();

        Assert.Empty(run.Ids);
        Assert.Equal(
            Lines("""
            // <auto-generated/>
            #nullable enable

            namespace Probe;

            /// <summary>
            /// The keys this project authors, generated from its <c>.resx</c>. The resource file is the
            /// declaration: a key renamed there moves this with it, and a producer naming one that is no
            /// longer authored stops compiling.
            /// </summary>
            public static class ProbeKeys
            {
                /// <summary>The resource set these keys are authored in.</summary>
                public const string ResourceName = "Probe.Strings";

                /// <summary>A catalog over this resource set, for <paramref name="cultures"/>.</summary>
                public static global::SimpleLocalizations.StringCatalog Catalog(
                    global::SimpleLocalizations.TextCultures cultures) =>
                    cultures.Catalog(ResourceName, typeof(ProbeKeys).Assembly);

                /// <summary>The <c>alpha</c> family.</summary>
                public static class Alpha
                {
                    /// <summary>The stem every key in this family shares.</summary>
                    public const string Prefix = "alpha.";

                    /// <summary>Whether <paramref name="key"/> belongs to this family.</summary>
                    public static bool Covers(string key) =>
                        key.StartsWith(Prefix, global::System.StringComparison.Ordinal);

                    /// <summary>Names a &amp; b, where a &lt; b &gt; c.</summary>
                    public static global::Probe.ProbeKey One =>
                        global::Probe.ProbeKey.From("alpha.one");

                    /// <summary>The <c>alpha.prefix</c> entry.</summary>
                    public static global::Probe.ProbeKey PrefixKey =>
                        global::Probe.ProbeKey.From("alpha.prefix");

                }

                /// <summary>The <c>beta</c> family.</summary>
                public static class Beta
                {
                    /// <summary>The stem every key in this family shares.</summary>
                    public const string Prefix = "beta.";

                    /// <summary>Whether <paramref name="key"/> belongs to this family.</summary>
                    public static bool Covers(string key) =>
                        key.StartsWith(Prefix, global::System.StringComparison.Ordinal);

                    /// <summary>The <c>beta.deep</c> family.</summary>
                    public static class Deep
                    {
                        /// <summary>The stem every key in this family shares.</summary>
                        public const string Prefix = "beta.deep.";

                        /// <summary>Whether <paramref name="key"/> belongs to this family.</summary>
                        public static bool Covers(string key) =>
                            key.StartsWith(Prefix, global::System.StringComparison.Ordinal);

                        /// <summary>The <c>beta.deep.three</c> entry.</summary>
                        public static global::Probe.ProbeKey Three =>
                            global::Probe.ProbeKey.From("beta.deep.three");

                    }

                }

                /// <summary>The <c>detail</c> family.</summary>
                public static class Detail
                {
                    /// <summary>The stem every key in this family shares.</summary>
                    public const string Prefix = "detail.";

                    /// <summary>Whether <paramref name="key"/> belongs to this family.</summary>
                    public static bool Covers(string key) =>
                        key.StartsWith(Prefix, global::System.StringComparison.Ordinal);

                    /// <summary>The <c>detail.1password</c> entry.</summary>
                    public static global::Probe.OtherKey _1password =>
                        global::Probe.OtherKey.From("detail.1password");

                }

                /// <summary>The <c>greeting</c> entry.</summary>
                public static global::Probe.ProbeKey Greeting =>
                    global::Probe.ProbeKey.From("greeting");

            }

            """),
            Lines(run.OnlySource));
    }

    [Fact]
    public void The_document_opens_with_the_two_lines_a_generated_file_carries()
    {
        var lines = Lines(Emitted().OnlySource).Split('\n');

        Assert.Equal("// <auto-generated/>", lines[0]);
        Assert.Equal("#nullable enable", lines[1]);
    }

    [Fact]
    public void Dropping_the_marker_turns_SL1010_on_the_one_caller_it_exempts()
    {
        // Why the first line is load-bearing, which it does not look. VocabularyKeyGuard asks not to see
        // generated code, and Roslyn decides what is generated partly from that marker — so without it the
        // rule fires on the generated declaration, which is the one caller allowed to produce a key.
        var emitted = Generate(Keys("greeting"), new Declaration("ProbeKeys", "Probe.ProbeKey", "Probe"))
            .OnlySource;

        Assert.Empty(Guarded(emitted));
        Assert.Equal(["SL1010"], Guarded(emitted.Replace("// <auto-generated/>", "")));
    }

    /// <summary>
    /// <see cref="VocabularyKeyGuard"/> over a generated vocabulary and the key types it names, as the two
    /// files a build holds them in.
    /// </summary>
    private static IEnumerable<string> Guarded(string emitted) =>
        AnalyzeFiles(new VocabularyKeyGuard(), KeyTypes, emitted).Select(diagnostic => diagnostic.Id);

    /// <summary>
    /// Text with its line endings normalized. The emitter writes the platform's and a checkout writes the
    /// platform's, so a comparison holding either would pin the platform rather than the output.
    /// </summary>
    private static string Lines(string text) => text.Replace("\r\n", "\n");
}
